services:
  app:
    container_name: server
    build:
      context: .
      dockerfile: ./dockerfiles/app/Dockerfile
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
