package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.26

import (
	"context"

	"github.com/koralle/lazy-warehouse/backend/graph/model"
	"github.com/koralle/lazy-warehouse/backend/internal"
)

// SetRoleToUserInGroup is the resolver for the setRoleToUserInGroup field.
func (r *mutationResolver) SetRoleToUserInGroup(ctx context.Context, input model.SetRoleInput) (*model.SetRoleResult, error) {
	return r.Srv.SetRoleToUserInGroup(ctx, input)
}

// GetAllAvailableRoles is the resolver for the getAllAvailableRoles field.
func (r *queryResolver) GetAllAvailableRoles(ctx context.Context) ([]*model.Role, error) {
	return r.Srv.GetAllAvailableRole(ctx)
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id model.UUID) (*model.Group, error) {
	return r.Srv.Group(ctx, id)
}

// Group is the resolver for the group field.
func (r *queryResolver) User(ctx context.Context, id model.UUID) (*model.User, error) {
	return r.Srv.User(ctx, id)
}

// Mutation returns internal.MutationResolver implementation.
func (r *Resolver) Mutation() internal.MutationResolver { return &mutationResolver{r} }

// Query returns internal.QueryResolver implementation.
func (r *Resolver) Query() internal.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
